### ISSUE TITLE
1.0 - Can't launch

### ISSUE THREAD

**Issue by Tyler799** [mlox/mlox#39] opened 2019-08-13 01:51 UTC
When I attempt to launch version 1.0 from Mod Organizer 2, the following happens:

1: A console window pops up briefly, and some text fills up

2: It closes itself

Others seem to be experiencing this as well. Just in case, I dropped it into my original MLOX folder with all the other files, and just over-wrote the EXE, but no joy.

What's up with this? I'm not sure if I do have Python installed, but it worked fine in the past. And it didn't give some warning that Python was missing when I tried to launch it.

**Comment by dvillwoc** [comment] 2019-08-13 21:53
I'm having the same issue. I managed to capture a screen grab of the error I'm getting

it states:

> Traceback (most recent call last):
File "mlox_works.py", line 5, in <module>
File "mlox\\\_\_main__.py", line 250, in main
File "mlox\\_\_main__.py", line 160, in build_parser
File "mlox\version.py", line 17, in about
File "mlox\version.py", line 67, in version_info
File "mlox\version.py", line 50, in requirement_status
File "subprocess.py", line 342, in check_call
File "subprocess.py", line 323, in call
File "subprocess.py", line 775, in \_\_init__
File "subprocess.py", line 1178, in _execute_child
FineNotFoundError: [WinError 2] The system cannot find the file specified
[288] Failed to execute script mlox_works


It was working from the download I had last week, but when I redownloaded today for reasons it no longer works, and unfortunately I no longer have the previous version. I see the update log states it was updated 2 days ago

**Comment by EmperorArthur** [comment] 2019-08-15 12:04
You should not have to install 0.62 first, and don't even need Python any more unless you are running from source.

I have updated mlox.exe to a new version, and added installation instructions, but here's a summary. 
 The first thing to do is to **remove the "mlox" folder completely.** Then just put the new version of "mlox.exe" in your Morrowind directory.

If you want to use the "source" version, you can open an administrator command prompt and type `pip3 install mlox`.  Then, with your console's current directory in the Morrowind directory run `python -m mlox`.

Please let me know if this new release fixes your issue.

**Comment by TirigonX** [comment] 2019-08-15 19:17
Same problem here, fresh installation of Morrowind (steam version, Windows 10 version 1903), placed mlox in Morrowind folder an ran it, but nothing happened apart from what the users above already reported.

**Comment by EmperorArthur** [comment] 2019-08-16 02:15
Hmm, this is interesting @TirigonX , especially since the new exe I've placed in the release should have said something like:
> Failed to execute script __main__
Instead of what @dvillwoc saw, which is from the old one.

I'll try to get a multi-file build that you have to extract out this weekend to see if that fixes the problem everyone is having.

As I work on getting that out, could I get you to try two different things to see what happens.

First:
* Open the program called `Command Prompt` (you can just start typing with the start menu open)
* Run `cd "C:\Program Files (x86)\Morrowind\"`, or to wherever Morrowind is installed.
* Type `mlox.exe`

Next, so the same steps as above, except right click on `Command Prompt` and select "Run as administrator".

I would really appreciate it if you could run those commands and paste the output here.

**Comment by TirigonX** [comment] 2019-08-17 09:49
Here you go. Last line is actually a bit different as you expected. I just couldn't read it before, because the window closed itself almost instantly.

D:\Games\Steam\SteamApps\common\Morrowind>mlox.exe
Traceback (most recent call last):
  File "mlox\__main__.py", line 309, in <module>
  File "mlox\__main__.py", line 250, in main
  File "mlox\__main__.py", line 160, in build_parser
  File "mlox\version.py", line 17, in about
  File "mlox\version.py", line 67, in version_info
  File "mlox\version.py", line 50, in requirement_status
  File "subprocess.py", line 342, in check_call
  File "subprocess.py", line 323, in call
  File "subprocess.py", line 775, in __init__
  File "subprocess.py", line 1178, in _execute_child
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
[388] Failed to execute script __main__

Running as admin:

D:\Games\Steam\SteamApps\common\Morrowind>mlox.exe
Traceback (most recent call last):
  File "mlox\__main__.py", line 309, in <module>
  File "mlox\__main__.py", line 250, in main
  File "mlox\__main__.py", line 160, in build_parser
  File "mlox\version.py", line 17, in about
  File "mlox\version.py", line 67, in version_info
  File "mlox\version.py", line 50, in requirement_status
  File "subprocess.py", line 342, in check_call
  File "subprocess.py", line 323, in call
  File "subprocess.py", line 775, in __init__
  File "subprocess.py", line 1178, in _execute_child
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
[8364] Failed to execute script __main__

**Comment by EmperorArthur** [comment] 2019-08-17 18:45
Thank you so much.  I was on the completely wrong track before.

# Problem cause
In order to get the latest rules file, mlox first checks, then downloads the latest rules from the internet.  To save bandwidth the rules file is a compressed 7z file.  To account for different situations, mlox can use multiple back-ends to extract the 7z file's contents, one of which is the 7-zip program.

There is a check to see if 7-zip works:
```
try:
    with open(os.devnull, 'w') as devnull:
        subprocess.check_call('7za', stdout=devnull)
        output["7-Zip"] = "Installed"
except subprocess.CalledProcessError:
    output["7-Zip"] = None
```

See the problem?  I didn't.

The problem is if the `7za` program does not exist, the error returned is actually different.  So the fix is:
```
except (subprocess.CalledProcessError, FileNotFoundError):
```

The worst part is, by default mlox uses a pure python file extractor, so this code only really does anything if the compression format changes.  It's a legacy of me working around a problem that I've completely solved.

# Why didn't this happen previously?
Previous versions of mlox actually bundled 7-zip with them, so no check was even needed.  The problem being that from a copyright perspective, I'm not sure if I am allowed to do that or not.

#The (hopeful solution)
[Download this version of mlox.exe](https://github.com/mlox/mlox/releases/download/v1.0/mlox.exe).  It is the latest uploaded to the release page.

Please let me know if this solves your issue.

**Comment by TirigonX** [comment] 2019-08-17 22:18
Sorry I tried the latest version but it's still not working. Same error as before.

**Comment by Tyler799** [comment] 2019-08-17 22:45
Unfortunately the new .exe doesn't help me either. Same thing: https://imgur.com/eipXqst

It pops up, then there's some text for a brief second, and then it's gone. There's no log file to speak of, so nothing much to report.

**Comment by EmperorArthur** [comment] 2019-08-17 23:15
@TirigonX Exact same error including line numbers? Does running `mlox.exe -v` from the Command Line do anything?

**Comment by Tyler799** [comment] 2019-08-18 00:41
@EmperorArthur Just tested. It still does the same thing, no gui ever appears. It may actually being some sorting (incorrectly, it tossed patch for purists at the end of my list), but I think it may have been before as well. It's hard to tell.

**Comment by TirigonX** [comment] 2019-08-18 12:07
It's working now, but only when run directly. It still doesn't work when run from within Mod Organizer 2.
I managed to run the command prompt from within MO and called mlox. This is the output (I'm also adding a screenshot since github's formatting removes some bits of text)

D:\>games\steam\steamapps\common\morrowind\mlox.exe
Traceback (most recent call last):
  File "mlox\__main__.py", line 309, in <module>
  File "mlox\__main__.py", line 250, in main
  File "mlox\__main__.py", line 160, in build_parser
  File "mlox\version.py", line 17, in about
  File "mlox\version.py", line 67, in version_info
  File "mlox\version.py", line 42, in requirement_status
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\arthur\.virtualenvs\mlox-um-olkwo\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\libarchive\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\arthur\.virtualenvs\mlox-um-olkwo\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\libarchive\entry.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\arthur\.virtualenvs\mlox-um-olkwo\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\libarchive\ffi.py", line 108, in <module>
  File "site-packages\libarchive\ffi.py", line 95, in ffi
  File "ctypes\__init__.py", line 369, in __getattr__
  File "ctypes\__init__.py", line 374, in __getitem__
AttributeError: function 'archive_errno' not found
[2936] Failed to execute script __main__


![mloxmoerror](https://user-images.githubusercontent.com/8441677/63224231-7ce8ef00-c1c1-11e9-9a22-df632d2867bc.jpg)

**Comment by EmperorArthur** [comment] 2019-08-18 20:11
For things like code you should be able to highlight your text and use use the "<>" from the menu.  That should fix GitHub eating the formatting.

This is a new variation on exactly the same problem.  Aside from "7-zip" the next program checked is something called "libarchive".  In that case it's looking for a dll file that I haven't bundled with the system, for the same reason I haven't included 7-zip.  I handled the case of that one missing, but didn't think about what happens if it finds the dll, but something goes wrong after that.

I have once again updated the exe file, so **please try it one more time**.

I really should have done a release candidate instead of calling it 1.0 immediately, but got ahead of myself.

**Comment by TirigonX** [comment] 2019-08-19 10:43
Yes! It's working with Mod Organizer now as well. Thank you very much!

**Closed** 2019-09-23 02:44 UTC
